### PR TITLE
Implement new joint-prob figure discussed at AGU

### LINKED ISSUE #72: Figure 3 changes
Implement the joint probability distribution idea we discussed at AGU?

GPP on x, Rs on y

### PR DESCRIPTION
**Pull request by bpbond**
Closes #72

### CODE REVIEW

**Comment by bpbond** [comment]
@jinshijian See the subscripts I added to the figure legend.

**Comment by bpbond** [comment]
Figure3_not_sure

**Comment by abigailsnyder** [comment]
I think it works if 1-2 more arrows are annotated onto the dashed lines and maybe more text is included in the legend. 'Joint pdf with Rs driven GPP' and 'Joint pdf with GPP driven Rs' might be more direct than the 'Bootstrap data source = GPP/Rs'?
But overall, once I'm oriented in the figure, it does convey that clear, appreciable differences exist in the estimates. The nearly disjoint nature of the two joint pdfs is really striking

**Comment by jinshijian** [comment]
I agree with @abigailsnyder 
For the arrows, we can also try solid lines and see whether it works.

**Comment by jinshijian** [comment]
image
I think the solid line with arrows looks better

**Pull request merged**
